### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Hackman238** [Hackman238/legion#23]
Hello! I'm trying to run Legion 0.3.7 on Kali Linux, but it is crashing with the following errors upon scanning a host:

Traceback (most recent call last):
  File "/usr/share/legion/app/importers/NmapImporter.py", line 283, in run
    scrProcessorResults = scr.scriptSelector(db_host)
  File "/usr/share/legion/parsers/Script.py", line 122, in scriptSelector
    cveResults = self.getCves()
  File "/usr/share/legion/parsers/Script.py", line 96, in getCves
    cvesResults = self.processVulnersScriptOutput(cveOutput)
  File "/usr/share/legion/parsers/Script.py", line 66, in processVulnersScriptOutput
    resultCpeDetails['version'] = resultCpeData[4]
IndexError: list index out of range
zsh: IOT instruction  legion

Thanks!

**Comment by Hackman238** [comment]
Fixed in latest.
