### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str (LEgion crashes)

### ISSUE THREAD

**Issue by sagisar1** [Hackman238/legion#32]
Hello, I got the following error described in the description. legion opens, but when enetering a host to scan, after a while it crashes. I ma using the native binary of kali linux, not from the repository.
OS: **kali linux 2024.4**
python version -  **3.12.7**
Legion version (indicated by the help utility in legion )   -   **0.4.3-1700529501**

full Error is below:

```
[13:14:51] INFO     Creating temporary project at application start...               legion.py:145
[13:14:52] INFO     Established SQLite connection on file                    SqliteDbAdapter.py:58
                    '/root/.local/share/legion/tmp/legion-kxbq58b9.legion'                        
           INFO     Wordlist was created/opened:                                  auxiliary.py:186
                    /root/.local/share/legion/tmp/legion-of4y99l7-tool-output/leg                 
                    ion-usernames.txt                                                             
           INFO     Wordlist was created/opened:                                  auxiliary.py:186
                    /root/.local/share/legion/tmp/legion-of4y99l7-tool-output/leg                 
                    ion-passwords.txt                                                             
[13:14:53] INFO     Loading settings file..                                         settings.py:37
           INFO     Legion started successfully.                                     legion.py:165
[13:19:04] INFO     runStagedNmap called for stage 1                             controller.py:773
           INFO     Adding process: <db.entities.process.process object at ProcessRepository.py:69
                    0x7f168fe78f20>                                                               
           INFO     Queuing: nmap -T4 -sV -sSU -O -p                             controller.py:704
                    T:80,81,443,4443,8080,8081,8082 -vvvv 10.129.132.79 -oA                       
                    /root/.local/share/legion/tmp/legion-24b0cuoz-running/nmap/2                  
                    0241204131904920302-nmapstage1                                                
           INFO     Running: nmap -T4 -sV -sSU -O -p                             controller.py:624
                    T:80,81,443,4443,8080,8081,8082 -vvvv 10.129.132.79 -oA                       
                    /root/.local/share/legion/tmp/legion-24b0cuoz-running/nmap/2                  
                    0241204131904920302-nmapstage1                                                
[13:19:05] INFO     runCommand called for stage 1                                controller.py:724
           INFO     runCommand connected for stage 1                             controller.py:727
[13:19:35] INFO     Process 1 is done!                                           controller.py:882
           INFO     Storing process output into db:                        ProcessRepository.py:86
                    <db.entities.processOutput.process_output object at                           
                    0x7f168f543fb0>                                                               
           INFO     Halting process panel update timer as all processes are      controller.py:639
                    finished.                                                                     
           INFO     runStagedNmap called for stage 2                             controller.py:773
           INFO     Adding process: <db.entities.process.process object at ProcessRepository.py:69
                    0x7f168f5a5a00>                                                               
           INFO     Queuing: nmap -T4 -sV -sSU -O -p                             controller.py:704
                    T:25,135,137,139,445,1433,3306,5432,U:137,161,162,1434 -vvvv                  
                    10.129.132.79 -oA                                                             
                    /root/.local/share/legion/tmp/legion-24b0cuoz-running/nmap/2                  
                    0241204131935926471-nmapstage2                                                
           INFO     Running: nmap -T4 -sV -sSU -O -p                             controller.py:624
                    T:25,135,137,139,445,1433,3306,5432,U:137,161,162,1434 -vvvv                  
                    10.129.132.79 -oA                                                             
                    /root/.local/share/legion/tmp/legion-24b0cuoz-running/nmap/2                  
                    0241204131935926471-nmapstage2                                                
[13:19:36] INFO     runCommand called for stage 2                                controller.py:724
           INFO     runCommand connected for stage 2                             controller.py:727
Traceback (most recent call last):
  File "/usr/share/legion/ui/view.py", line 1442, in updateInterface
    self.updateHostsTableView()
  File "/usr/share/legion/ui/view.py", line 1053, in updateHostsTableView
    self.HostsTableModel.sort(3, Qt.SortOrder.DescendingOrder)
  File "/usr/share/legion/ui/models/hostmodels.py", line 140, in sort
    array.append(IP2Int(self.__hosts[i]['ip']))
                        ~~~~~~~~~~~~~~~^^^^^^
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 54, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
zsh: IOT instruction  sudo legion

```

**Comment by sagisar1** [comment]
@Hackman238 Dude, is there any update? it's been a month and you havn't say anything

**Comment by fghdsfds** [comment]
Gemini fixed this issue for me.

The core problem was a recurring TypeError. This error happened because the code was trying to access data from database query results (which often come as special objects, like SQLAlchemy RowProxy objects) as if they were simple Python dictionaries (e.g., data_object['some_key']).

However, these objects actually need to be accessed either like attributes (e.g., data_object.some_key) or like tuples with numbered items.

To fix this, we had to manually edit three Python files that define how Legion handles and displays data in its tables:

hostmodels.py: This file manages how host information (IPs, OS, etc.) is displayed and sorted. We changed all instances where it tried to get data like host['ip'] to host.ip (or more safely, getattr(host, 'ip', default_value))

servicemodels.py: This file handles the display of services found on hosts (ports, protocols, service names, banners). The same type of fix was applied here, changing service['portId'] to service.portId, and so on for all data points.

processmodels.py: This file manages the "Processes" tab, showing running Nmap scans and other tools Legion launches. Again, we updated the code to use attribute access (e.g., process.pid instead of process['pid']) for all process-related data.

In essence, the fixes involved:

Changing Data Access Method: Systematically replacing all dictionary-style key lookups (object['key']) with attribute-style access (object.key or getattr(object, 'key')).

Adding Robustness: Using getattr(object, 'key', default_value) or hasattr(object, 'key') checks to prevent errors if an expected piece of data was missing for a particular host, service, or process.

Ensuring Correct Data Types: Making sure that data used for sorting (like port numbers) was converted to the correct type (e.g., integer) before being used.

Improving Error Handling: In some places, adding try-except blocks to catch unexpected issues during data processing or sorting, logging the error instead of letting the application crash.

**Comment by sagisar1** [comment]
@fghdsfds 
1. can you be more specific about the changes in hostmodels.py , since i don't see -- but strings like hosts[i]['ip'], self.__hosts[row]['ip'] etc. in the original code
2. the same request for servicemodels.py, because i see  value = self.__services[row]['portId']
3. and again for processmodels.py

if this is too complicated, maybe you can submit a pull request to @Hackman238

**Comment by Hackman238** [comment]
Fixed in the latest.
